### ISSUE TITLE
noticeboard.git の方にREADME用意する

### ISSUE THREAD

**Issue by F88** [codeforjapan/noticeboard#1]
[Home · codeforjapan/noticeboard Wiki](https://github.com/codeforjapan/noticeboard/wiki) が用意されたがやはり noticeboard.git/README.md 等は必要だと思うので用意する。

**Comment by F88** [comment]
どんなこと書いておくべきでしょうかね。

今後どう使って行くかという所次第ですが、もろもろ扱うWikiという扱いにするのであればその旨記載しておくのもよさそうです。

**Comment by homata** [comment]
WIkiに関する説明で良いのではないですかね

**Comment by homata** [comment]
REAME.mdは作成しておきました。
記述する内容については、これから決めていきたいです
