### ISSUE TITLE
TrelloのGitHub参考文献まとめるカードをGitHub Issue化する

### ISSUE THREAD

**Issue by F88** [codeforjapan/noticeboard#3]
GitHub入門のための参考文献まとめる on Code for Japan | Trello
https://trello.com/c/KWylNsON

**Comment by F88** [comment]
Trelloのカードにも書いてあるように元のカードの目的は特定の勉強会の為の情報整理だったので、これをGitHubなりのWikiにまとめるのは以下の観点からうまくないと思っています。
- GitHub入門なんてものは数年も経てば陳腐化して逆に混乱する

もしWikiのようなものにまとめる場合は、 **xxxx-xx-xx勉強会用資料** としてまとめることでその内容が特定時期の特定の目的の為に用意されたものであることは最低限明示すべきかなと。

**Comment by F88** [comment]
カード中に @chokkoyamada さんもコメントされているように

> 講座の目標をどこに置くか、ですが「使いこなせるようになる」だとだいぶ敷居高くて期待値高くしすぎかもしれないですね。>GitHubにどういう機能があって、どういうことができるのか、普通どう使われているのかを見てもらいながら、手を動かせるところを実際にやってもらうくらいの感じでやろうかと思います。

ってところも味噌だと思います。

GitHubの使い方は時期や組織によっても家なり異なるので、3年、10年とずっと有用な情報を整理してまとめるっていうのは現実的に無理だと思います。

**Comment by F88** [comment]
とここまで書いて思ったのは Trello にある情報をGitHubに転記するのもなんか無駄だな,そもそもTrelloのカードへのリンク自体がここに記載されていればそれを参照すれば良いかなと。Trelloのカードはarchiveしてしまっても問題無いと思いますので対応しておきます。 @homata

**Comment by F88** [comment]
カードのタイトルをより分かりやすく **2013-11-15 GitHub入門のための参考文献まとめる** に変更しました。
- [2013-11-15 GitHub入門のための参考文献まとめる](https://trello.com/c/KWylNsON)

**Comment by homata** [comment]
まずは、TrelloのカードをCloseしたかったので、ありがとうございます。

GitHubの使い方は、そのうち勉強会でもしていきたいです
